### ISSUE TITLE
error CRM 2016 ON PREMISE RU2

### ISSUE THREAD

**Issue by talsimalam** [MscrmTools/MsCrmTools.AttributeBulkUpdater#1]
![image](https://cloud.githubusercontent.com/assets/25318581/22240283/0f7f92fa-e223-11e6-93fb-048c1e489968.png)
error message... when using SLAKPI fields on entity (or calculated fields)

**Comment by MscrmTools** [comment]
Seems more like an environment issue than a tool issue
