### ISSUE TITLE
Update attribute with copy of value from column in queried records?

### ISSUE THREAD

**Issue by Techek** [MscrmTools/MsCrmTools.AttributeBulkUpdater#2]
Once in a while I have a need for using a value from one or more columns to update specified attributes.

Would it be possible to introduce a fourth option "Copy" (next to Value, Touch and Set null) which allows me to reference a specific column in the queried records and use the value in the attribute? The fourth option could list all type-convertible/-compatible columns or just all columns.

**Comment by MscrmTools** [comment]
@Techek, I guess you are on the wrong repository... it should be [This one](https://github.com/rappen/BulkDataUpdater) from @rappen

**Comment by Techek** [comment]
Thank you for clearing this up! You could have fooled me. ;)
