### ISSUE TITLE
New Button: Invert selection 

### ISSUE THREAD

**Issue by maeg02** [MscrmTools/MsCrmTools.AttributeBulkUpdater#3]
A common scenario is to remove fields from advanced find, this tool is great at that.
It would be even better if it was possible to remove all attributes that Not included in any form.
To achieve this it could be good with an "Invert selection" button, then users could press "check Attr. on Forms" then "Invert selection, and then remove the "Valid for Adv. Find".

Would it be possible to have a new button "Invert selection" to easy do this scenario?

**Comment by MscrmTools** [comment]
For sure! That is possible.
