### ISSUE TITLE
separate options for selecting and for updating

### ISSUE THREAD

**Issue by maeg02** [MscrmTools/MsCrmTools.AttributeBulkUpdater#5]
Would it be usefull if the tool had options for not updating some attributes, and thus not chaning some values.
Consider if you only want to change "valid for advanced find" and you do not want to change "audit" for that field.
So instead of a check box, there is a drop down with three values: "Do Not Change", "Set", "Unset"?

**Comment by MscrmTools** [comment]
It is already the way the tool works.
ticking a checkbox to select a property just means that ticked attributes will be updated with "true" value and no ticked one will be updated with "false" value. Of course, only attributes that have their property changed are updated.

**Comment by maeg02** [comment]
This is to mimic the solution already built for Requirement level.

If I have a bunch of fields that I want to change "searchable" for that already have a variety of audit enabled and disabled, so I do not change the "Auditing" or is secure. How do I achieve this?

**Comment by MscrmTools** [comment]
Load attributes
Tick only "Valid for adv. find" checkbox
In the attributes list, tick those that need to be searchable, untick those who don't need to be searchable
Click on "Save attributes" button
You're done

**Comment by maeg02** [comment]
Now, you have also reset audit and secure properties on the ticked fields to disabled.
Currently there is no way to only set one of the three properties.
My suggestion will enable this.
Regards Markus

**Comment by MscrmTools** [comment]
Si that is more a bug

**Comment by maeg02** [comment]
Please take a look at the suggested PR and give me feedback, we can do it!

**Comment by MscrmTools** [comment]
I'm sorry to insist but the following code shows the behavior you see should not (cannot?) happen

How checkboxes state is saved in an `UpdateSettings` object
```
var us = new UpdateSettings
{
    Items = lvAttributes.Items.Cast<ListViewItem>().Select(i => (ListViewItem)i.Clone()).ToList(),
    UpdateValidForAdvancedFind = chkValidForAdvancedFind.Checked,
    UpdateAuditIsEnabled = chkValidForAudit.Checked,
    UpdateRequirementLevel = chkRequirementLevel.Checked,
    RequirementLevelValue = chkRequirementLevel.Checked ? MapSdkValue(cboRequirementLevel.SelectedIndex) : null,
    UpdateIsSecured = chkIsSecured.Checked
};

```

And how these settings are used when it comes to updating `AttributeMetadata` properties

 ```
if (us.UpdateValidForAdvancedFind)
{
    amd.IsValidForAdvancedFind.Value = item.Checked;
}

if (us.UpdateAuditIsEnabled)
{
    amd.IsAuditEnabled.Value = item.Checked;
}

if (us.UpdateRequirementLevel && us.RequirementLevelValue.HasValue)
{
    amd.RequiredLevel = new AttributeRequiredLevelManagedProperty(us.RequirementLevelValue.Value);
}

if (us.UpdateIsSecured)
{
    amd.IsSecured = item.Checked;
}

innerService.Execute(new UpdateAttributeRequest
{
    Attribute = amd,
    EntityName = amd.EntityLogicalName
});

```

**Comment by maeg02** [comment]
Hi Tanguy
Sorry to bother you, yes you are correct! This was just a misunderstanding on how to use this plugin tool.
the selection and updating are the same, so therefore it gets confusing.
Works as intended!
